SUPPORTED_OS =	OpenBSD 6.8 amd64
SUPPORTED_OS +=	OpenBSD 6.8 i386
SUPPORTED_OS +=	OpenBSD 6.9 amd64
SUPPORTED_OS +=	OpenBSD 6.9 i386

SKEL_kernel =	skel-kernel
SKEL_base =	skel-base

.include "../Makefile.inc"
